# animation of explosion using 2D sprite sheet

import simpleguitk as simplegui

# load 81 frame sprite sheer for explosion - image generated by phaedy explosion generator, source is hasgraphics.com
EXPLOSION_CENTER = [64, 64]
EXPLOSION_SIZE = [128, 128]

explosion_image = simplegui.load_image(
    "http://commondatastorage.googleapis.com/codeskulptor-assets/lathrop/explosion_orange.png")

# create ir that iterates current_sprite_center through sprite
time = 0

# define draw handler
def draw(canvas):
    global time
    i = time % 9

    canvas.draw_image(explosion_image,
                      [EXPLOSION_CENTER[0] + i * EXPLOSION_SIZE[0], EXPLOSION_CENTER[1]],
                      EXPLOSION_SIZE, EXPLOSION_CENTER, EXPLOSION_SIZE)
    time += 1

# create frame and size frame based on 100x100 pixel sprite
f = simplegui.create_frame("Asteroid sprite", EXPLOSION_SIZE[0], EXPLOSION_SIZE[1])

# set draw handler and canvas background using custom HTML color
f.set_draw_handler(draw)
f.set_canvas_background("Blue")

# start animation
f.start()